### ISSUE TITLE
Portfolio API Problems

### ISSUE THREAD

**Issue by kmonterr** [18F/nsf-sbir#775] opened 2017-07-31 21:13 UTC
Hi Brian,

It looks like the API on the portfolio page still isn't pulling some Phase II awards. I noticed it for Branch Technology and Altaeros Energy. Do you mind taking a look again?

related to closed issue #706

**Comment by gemfarmer** [comment] 2017-08-07 15:33
Looking at this now!

**Comment by gemfarmer** [comment] 2017-08-07 15:45
@kmonterr this is the API queries we are making for Branch Technology LLC and Altaeros Energy. It looks like Branch only returns one result, and it is for phase I and Altaeros returns. This is consistent with how both are being represented on the dev branch of the site. [Branch](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/portfolio/details/?company=branch-technology-llc) | [Altaeros](https://federalist-proxy.app.cloud.gov/preview/18f/nsf-sbir/dev/portfolio/details/?company=altaeros-energies-inc)

**Branch Technology:**
http://api.nsf.gov/services/v1/awards.json?agency=nsf&printFields=id%2CawardeeName%2Cdate%2CexpDate%2CfundsObligatedAmt%2CfundProgramName%2CpoName%2Ctitle%2CabstractText%2CstartDate%2CendDate%2CawardeeCity%2CawardeeCountryCode%2CawardeeStateCode%2CawardeeZipCode%2CawardeeAddress%2CpiFirstName%2CpiMiddeInitial%2CpiLastName%2CpiPhone%2CpiEmail&offset=1&expDateEnd=08%2F07%2F2017&awardeeName=branch+technology+llc&fundProgramName=phase

**Altaeros:**
http://api.nsf.gov/services/v1/awards.json?agency=nsf&printFields=id%2CawardeeName%2Cdate%2CexpDate%2CfundsObligatedAmt%2CfundProgramName%2CpoName%2Ctitle%2CabstractText%2CstartDate%2CendDate%2CawardeeCity%2CawardeeCountryCode%2CawardeeStateCode%2CawardeeZipCode%2CawardeeAddress%2CpiFirstName%2CpiMiddeInitial%2CpiLastName%2CpiPhone%2CpiEmail&offset=1&expDateEnd=08%2F07%2F2017&awardeeName=altaeros+energies+inc&fundProgramName=phase

**Comment by gemfarmer** [comment] 2017-08-07 15:45
Could it be that they have phase IIs that are more recent?

**Comment by kmonterr** [comment] 2017-08-07 15:54
Welcome back, @gemfarmer ! That's probably it...they are both still current grantees -
Branch - https://nsf.gov/awardsearch/showAward?AWD_ID=1632267&HistoricalAwards=false
Altaeros - https://www.nsf.gov/awardsearch/showAward?AWD_ID=1430989

**Comment by gemfarmer** [comment] 2017-08-07 15:58
Thanks! Based on that finding is this still an issue, or should we close it for now?

**Comment by gemfarmer** [comment] 2017-08-07 16:00
I mostly say this because it looks like the method for querying the API makes sense. Any result that isn't accurate is more likely to be caused by an issue with the API itself.

**Comment by kmonterr** [comment] 2017-08-07 16:28
Gotchya. Would it be possible to update the API to allow any company on the portfolio page with a current award to show their current award? It makes it inaccurate just to show one of their awards...

**Comment by gemfarmer** [comment] 2017-08-07 16:39
That can be done. For some reason I thought we wanted to keep them separate, but I include all results in the portfolio pages.

**Comment by gemfarmer** [comment] 2017-08-07 17:01
Updated this here: #786

**Comment by kmonterr** [comment] 2017-08-07 20:28
Thanks, @gemfarmer

**Closed** 2017-08-14 14:57 UTC
Labels: dev
